api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'about_mes', views.AboutMeViewSet)

# Wire up your API using automatic URL routing.
# Additionally, you include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

jb_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from music import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('spotify/login/', views.spotify_auth, name='spotify_auth'),
    path('spotify/callback/', views.spotify_callback, name='spotify_callback'),
    path('profile/', views.get_user_profile, name='profile'),
    path('playlist/', views.get_playlist, name='playlist'),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views



app_name = 'projects'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('projects/', views.ProjectIndexView.as_view(), name='projects'),
    path('projects/<slug:slug>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('resume/', views.view_pdf, name='view_pdf'),
]

projects/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower

# Create your models here.

class AboutMe(models.Model):
    """Model representing About Me information"""
    tag_line_text = models.CharField(max_length=200)
    main_text = models.TextField()
    # add resume link
    # resume = models.FileField(upload_to='files/', null=True, blank=True)
    

class Skill(models.Model):
    """Model representing technology used for a Project."""
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a particular Skill instance."""
        return reverse('skill-detail', args=[str(self.id)])
    
    class Meta:
        ordering = ['name']
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='skill_name_case_insensitive_unique',
                violation_error_message= "Skill already exists (case insensitive match)"
            ),
        ]

class Project(models.Model):
    """Model representing a Project."""
    title = models.CharField(max_length=100)
    description = models.TextField()
    skill = models.ManyToManyField(Skill, help_text="Select a skill used for this project.")
    slug = models.SlugField(unique=True, null=True, blank=True)
    preview_image = models.ImageField(upload_to='images/previews/', null=True, blank=True)
    animated_gif = models.ImageField(upload_to='images/gifs/', null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    highlight = models.BooleanField(default=False)
    

    def save(self, *args, **kwargs):
        """overwrites the internal save() method to automatically create a slug, if not provided."""
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this project."""
        return reverse('project-detail', args=[str(self.slug)])
    
    def display_skill(self):
        """Create a string for the Skill.  This is required to display the skill in Admin."""
        return ', '.join(skill.name for skill in self.skill.all())
    
    def skills_as_list(self):
        """Returns the name of each Skill used for this project."""
        return (skill.name for skill in self.skill.all())
    
    display_skill.short_description = 'Skill'

projects/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

projects/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .models import Project, Skill, AboutMe
from .forms import ContactForm
from django.template.loader import render_to_string
from django.views import generic
from django.http import FileResponse, Http404


class HomePageView(generic.ListView):
    model = Project
    template_name = 'projects/homepage.html'

class ProjectIndexView(generic.ListView):
    model = Project
    template_name = 'projects/index.html'

class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'projects/detail.html'

def contact(request):
    """View function for sending a email through contact form."""
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            hmtl = render_to_string('projects/emails/contact_form.html', {
                'name': name,
                'email': email,
                'message': message
            })

            send_mail('Message from Portfolio contact page.', 'This is the message', email, ['jake.bestland@gmail.com'], html_message = hmtl)

            return redirect('/contact')
        
    else:
        form = ContactForm()
    return render(request, 'projects/contact.html', {'form': form})

def about(request):
    """View function for about me page."""
    skills = Skill.objects.all()
    text = AboutMe.objects.get(id=1)
    context = {
        'skills': skills,
        'text': text
    }
    return render(request, 'projects/about.html', context=context)

def view_pdf(request):
    try:
        return FileResponse(open('media/files/resume.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jake Bestland</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'projects/css/style.css' %}">
    <style>
      hr {
        border: none;
        border-top: 5px solid #0FFCBE;
        color: #0FFCBE;
        overflow: visible;
        text-align: center;
        height: 5px;
      }

      hr::after {
        background: #106EBE;
        content: 'Some of my latest work';
        padding: 0 4px;
        position: relative;
        top: -13px;
      }
    </style>
</head>
<body>
  <nav class="navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'projects:homepage' %}">
        <img src="{% static 'projects/img/Headshots.png' %}" alt="Logo" width="50" height="60" class="d-inline-block text-fs-2">
        <strong>Jake Bestland</strong>
      </a>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projects:homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projects:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projects:projects' %}">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projects:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="content">
  {% block content %}
  {% endblock %}
  </div>

  <footer class="footer">
    <div class="d-flex justify-content-between">
      <p>© 2024 Jake Bestland</p>
      <p><em><small>Built with Python, Django and Bootstrap, deployed on AWS.</small></em></p>
      <ul>
        <li class="nav-item">
          <a href="{% url 'projects:homepage' %}">Home</a>
        </li>
        <li>
          <a href="{% url 'projects:about' %}">About</a>
        </li>
        <li>
          <a href="{% url 'projects:projects' %}">Projects</a>
        </li>
        <li>
          <a href="{% url 'projects:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </footer>
</body>
</html>