api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'about_mes', views.AboutMeViewSet)

# Wire up your API using automatic URL routing.
# Additionally, you include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

jb_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from music import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('spotify/login/', views.spotify_auth, name='spotify_auth'),
    path('spotify/callback/', views.spotify_callback, name='spotify_callback'),
    path('profile/', views.get_user_profile, name='profile'),
    path('playlist/', views.get_playlist, name='playlist'),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views



app_name = 'projects'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('projects/', views.ProjectIndexView.as_view(), name='projects'),
    path('projects/<slug:slug>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('resume/', views.view_pdf, name='view_pdf'),
]

projects/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower

# Create your models here.

class AboutMe(models.Model):
    """Model representing About Me information"""
    tag_line_text = models.CharField(max_length=200)
    main_text = models.TextField()
    # add resume link
    # resume = models.FileField(upload_to='files/', null=True, blank=True)
    

class Skill(models.Model):
    """Model representing technology used for a Project."""
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a particular Skill instance."""
        return reverse('skill-detail', args=[str(self.id)])
    
    class Meta:
        ordering = ['name']
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='skill_name_case_insensitive_unique',
                violation_error_message= "Skill already exists (case insensitive match)"
            ),
        ]

class Project(models.Model):
    """Model representing a Project."""
    title = models.CharField(max_length=100)
    description = models.TextField()
    skill = models.ManyToManyField(Skill, help_text="Select a skill used for this project.")
    slug = models.SlugField(unique=True, null=True, blank=True)
    preview_image = models.ImageField(upload_to='images/previews/', null=True, blank=True)
    animated_gif = models.ImageField(upload_to='images/gifs/', null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    highlight = models.BooleanField(default=False)
    

    def save(self, *args, **kwargs):
        """overwrites the internal save() method to automatically create a slug, if not provided."""
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this project."""
        return reverse('project-detail', args=[str(self.slug)])
    
    def display_skill(self):
        """Create a string for the Skill.  This is required to display the skill in Admin."""
        return ', '.join(skill.name for skill in self.skill.all())
    
    def skills_as_list(self):
        """Returns the name of each Skill used for this project."""
        return (skill.name for skill in self.skill.all())
    
    display_skill.short_description = 'Skill'

projects/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

projects/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .models import Project, Skill, AboutMe
from .forms import ContactForm
from django.template.loader import render_to_string
from django.views import generic
from django.http import FileResponse, Http404


class HomePageView(generic.ListView):
    model = Project
    template_name = 'projects/homepage.html'

class ProjectIndexView(generic.ListView):
    model = Project
    template_name = 'projects/index.html'

class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'projects/detail.html'

def contact(request):
    """View function for sending a email through contact form."""
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            hmtl = render_to_string('projects/emails/contact_form.html', {
                'name': name,
                'email': email,
                'message': message
            })

            send_mail('Message from Portfolio contact page.', 'This is the message', email, ['jake.bestland@gmail.com'], html_message = hmtl)

            return redirect('/contact')
        
    else:
        form = ContactForm()
    return render(request, 'projects/contact.html', {'form': form})

def about(request):
    """View function for about me page."""
    skills = Skill.objects.all()
    text = AboutMe.objects.get(id=1)
    context = {
        'skills': skills,
        'text': text
    }
    return render(request, 'projects/about.html', context=context)

def view_pdf(request):
    try:
        return FileResponse(open('media/files/resume.pdf', 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()

projects/templates/projects/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}



<div class="px-4 py-5 text-center bg-gradient">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-normal"><strong>About Me</strong></h1>
            <p class="lead">{{ text.tag_line_text }}</p>
            <a href="{% url 'projects:view_pdf' %}" class="btn btn-primary" style="background-color: #0FFCBE; color: #106EBE;" target="_blank">Resume</a>
        </div>
    </div>
</div>

<div class="container text-center">
    <div class="row justify-content-evenly">
        <div class="col-4">
            <h2 class="fw-light"><strong>Who Am I?</strong></h2><br>
            <p class="lead text-start fs-5" style="white-space: pre-wrap">{{ text.main_text }}</p>
        </div>
        <div class="col-4">
            <h2 class="fw-light"><strong>Skills:</strong></h2><br>
            <p class="fs-3 lh-lg">
                {% for skill in skills %}
                <span class="badge rounded-pill" style="background-color: #0FFCBE; color: #106EBE;">{{ skill.name }}</span>
                {% endfor %}
            </p>
        </div>
    </div>
</div>

<br>
<br>

<div class="container text-center">
    <h2 class="fw-light"><strong>Check Out My Spotify:</strong></h2>
    <div class="d-grid gap-3 d-sm-flex justify-content-center">
        <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="{% url 'profile' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-spotify fs-1" viewBox="0 0 16 16">
                <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0m3.669 11.538a.5.5 0 0 1-.686.165c-1.879-1.147-4.243-1.407-7.028-.77a.499.499 0 0 1-.222-.973c3.048-.696 5.662-.397 7.77.892a.5.5 0 0 1 .166.686m.979-2.178a.624.624 0 0 1-.858.205c-2.15-1.321-5.428-1.704-7.972-.932a.625.625 0 0 1-.362-1.194c2.905-.881 6.517-.454 8.986 1.063a.624.624 0 0 1 .206.858m.084-2.268C10.154 5.56 5.9 5.419 3.438 6.166a.748.748 0 1 1-.434-1.432c2.825-.857 7.523-.692 10.492 1.07a.747.747 0 1 1-.764 1.288"/>
              </svg>
              Click here
        </a>
    </div>

</div>


{% endblock %}

projects/templates/projects/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="px-4 py-5 text-center bg-gradient">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-normal"><strong>Contact</strong></h1>
            <p class="lead">Get in touch with me via social media or send me an email.</p>
            <div class="d-grid gap-3 d-sm-flex justify-content-center">
                <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://github.com/jake-bestland" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github fs-2" viewBox="0 0 16 16">
                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                      </svg>
                </a>
                <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://www.linkedin.com/in/jake-bestland/" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin fs-2" viewBox="0 0 16 16">
                        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                      </svg>
                </a>
                <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://x.com/worstwater" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x fs-2" viewBox="0 0 16 16">
                        <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                      </svg>
                </a>
                <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://www.facebook.com/jake.bestland/" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook fs-2" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                      </svg>
                </a>
            </div>
        </div>
    </div>
</div>


<form method="post" action=".">
    {% csrf_token %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <fieldset>
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="control-group error">
                                <span class="input-group-text" style="background-color: #0FFCBE;">{{ field.label }}:</span> 
                                <div class="controls">{{ field }}
                                    <span class="help-inline">
                                        {% for error in  field.errors %}{{ error }}{% endfor %}
                                    </span>
                                </div>
                            </div>
                        {% else %}
                            <div class="control-group mb-3">
                                <span class="input-group-text fs-4" style="white-space: pre; background-color: #0FFCBE; color: #106EBE;">{{ field.label }} :  {{ field }}</span> 
                                    {% if field.help_text %}
                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                    {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </fieldset>
                <div class="form-actions">
                    <button type="submit" class="btn btn-primary" style="background-color: #0FFCBE; color: #106EBE;">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>





{% endblock %}

projects/templates/projects/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <div class="px-4 py-5 text-center bg-gradient">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-normal"><strong>{{ project.title }}</strong></h1>
            <div class="gif-container d-inline-block">
              {% if project.preview_image %}
              <!-- Static Preview Image -->
              <img src="{{ project.preview_image.url }}" class="img-fluid preview" alt="Static Preview" width="100%" height="75%">
              {% endif %}
              {% if project.animated_gif %}
              <!-- Animated GIF -->
              <img src="{{ project.animated_gif.url }}" class="img-fluid animated" alt="Animated GIF" width="100%" height="75%">
              {% endif %}
            </div>
            <h4>About the project:</h4>
            <p class="lead">{{ project.description }}</p>
            <h4>Built with:</h4>
            <p>
                {% for skill in project.skills_as_list %}
                <span class="badge rounded-pill" style="background-color: #0FFCBE; color: #106EBE;">{{ skill }}</span>
                {% endfor %}
            </p>
            {% if project.link %}
            <a href="{{ project.link }}" class="btn btn-primary" style="background-color: #0FFCBE; color: #106EBE;" target="_blank">Project Link</a>
            {% endif %}
          </div>
        </div>
      </div>


{% endblock %}

projects/templates/projects/homepage.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="px-4 py-5 text-center bg-gradient">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-semibold">Hi, I'm Jake Bestland</h1>
            <p class="lead fw-normal fs-4">I'm a full stack python software engineer</p>
            <div class="d-grid gap-3 d-sm-flex justify-content-center">
            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://github.com/jake-bestland" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github fs-2" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                  </svg>
            </a>
            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://www.linkedin.com/in/jake-bestland/" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin fs-2" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                  </svg>
            </a>
            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://x.com/worstwater" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x fs-2" viewBox="0 0 16 16">
                    <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                  </svg>
            </a>
            <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="https://www.facebook.com/jake.bestland/" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook fs-2" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                  </svg>
            </a>
        </div>
        </div>
    </div>
</div>
<br>

<div class="container">
    <div class="row align-items-end">
        <div class="row justify-content-evenly">
            <hr>
            <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for project in project_list %}
                {% if project.highlight %}
                    <div class="col">
                        <div class="card h-100" style="background-color: #0FFCBE;">
                            <div class="gif-container d-inline-block">
                                {% if project.preview_image %}
                                <!-- Static Preview Image -->
                                <img src="{{ project.preview_image.url }}" class="img-fluid preview" alt="Static Preview" width="100%" height="300px">
                                {% endif %}
                                {% if project.animated_gif %}
                                <!-- Animated GIF -->
                                <img src="{{ project.animated_gif.url }}" class="img-fluid animated" alt="Animated GIF" width="100%" height="300px">
                                {% endif %}
                            </div>
                            <div class="card-body" style="background-color: #0FFCBE; color: #106EBE;">
                                <h5 class="card-title">{{ project.title }}</h5>
                                <p class="card-text">{{ project.description|capfirst|truncatechars:150 }}.</p>
                                <p class="card-text"><small><strong>Built with: </strong>{{ project.skill.all|join:", " }}</small></p>
                            </div>
                            <div class="card-footer" style="background-color: #0FFCBE; color: #106EBE;">
                                <a href="{% url 'projects:project_detail' project.slug %}" class="btn btn-primary" style="background-color: #106EBE; color: #0FFCBE;">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

projects/templates/projects/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="px-4 py-5 text-center bg-gradient">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-normal"><strong>Projects</strong></h1>
            <p class="lead">Check out the projects I've been working on.</p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-evenly">
        <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for project in project_list %}
            <div class="col gx-5">
                <div class="card mb-3"">
                    <div class="row g-0">
                        <div class="col-md-4" style="background-color: #0FFCBE;">
                            <div class="gif-container d-inline-block">
                                {% if project.preview_image %}
                                <!-- Static Preview Image -->
                                <img src="{{ project.preview_image.url }}" class="img-fluid preview" alt="Static Preview" width="100%" height="100%">
                                {% endif %}
                                {% if project.animated_gif %}
                                <!-- Animated GIF -->
                                <img src="{{ project.animated_gif.url }}" class="img-fluid animated" alt="Animated GIF" width="100%" height="100%">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-8" style="background-color: #0FFCBE; color: #106EBE;">
                            <div class="card-body">
                                <h5 class="card-title">{{ project.title }}</h5>
                                <p class="card-text">{{ project.description|capfirst|truncatechars:150 }}.</p>
                                <p class="card-text"><small><strong>Built with: </strong>{{ project.skill.all|join:", " }}</small></p>
                                <a href="{% url 'projects:project_detail' project.slug %}" class="btn btn-primary" style="background-color: #106EBE; color: #0FFCBE;">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}